/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Webgl.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.r1.geometry} material={materials.r1} position={[0, 0.67, 2.02]} scale={[1, 0.04, 1]} />
      <mesh geometry={nodes.r4.geometry} material={materials.r4} position={[9.33, 0.67, -80.19]} scale={0.56} />
      <mesh geometry={nodes.r5.geometry} material={materials.r5} position={[4.94, 0.67, 32.21]} scale={0.67} />
      <mesh geometry={nodes.r3.geometry} material={materials.r3} position={[0, 0.5, 0]} scale={0.67} />
      <mesh geometry={nodes.r9.geometry} material={materials.r9} position={[55.59, 0.67, -39.5]} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Webgl.glb')
