/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Webgl_tmp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.P_base.geometry} material={nodes.P_base.material} position={[44.84, 1.02, -44.45]} scale={[-58.63, 1, -58.63]} />
      <group position={[0, 1.75, 0]} scale={2.59}>
        <mesh geometry={nodes.Circle.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle_1.geometry} material={materials.P_red} />
      </group>
      <group position={[0, 1.65, -88.18]} scale={2.59}>
        <mesh geometry={nodes.Circle001.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.P_red} />
      </group>
      <group position={[70.72, 1.65, -88.18]} scale={2.59}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.P_red} />
      </group>
      <group position={[41.51, 1.65, -50.03]} scale={3.65}>
        <mesh geometry={nodes.Circle003.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials.P_red} />
      </group>
      <group position={[89.75, 1.65, -50.03]} scale={2.59}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials.P_red} />
      </group>
      <group position={[89.75, 1.65, -0.49]} scale={2.59}>
        <mesh geometry={nodes.Circle005.geometry} material={materials.P_base} />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials.P_red} />
      </group>
      <mesh geometry={nodes.R1.geometry} material={materials.r_1} position={[44.93, 1.75, 0.12]} scale={[40.31, 1.62, 0.6]} />
      <mesh geometry={nodes.R6.geometry} material={materials.r_6} position={[44.93, 1.75, -87.73]} scale={[40.31, 1.62, 0.6]} />
      <mesh geometry={nodes.R7.geometry} material={materials.r_7} position={[-0.56, 1.75, -44.1]} rotation={[0, Math.PI / 2, 0]} scale={[39.42, 1.62, 0.6]} />
      <mesh geometry={nodes.R4.geometry} material={materials.r_4} position={[18.51, 1.75, -24.53]} rotation={[0, 0.93, 0]} scale={[25.81, 1.62, 0.6]} />
      <mesh geometry={nodes.R2.geometry} material={materials.r_2} position={[88.12, 1.75, -24.21]} rotation={[0, Math.PI / 2, 0]} scale={[19.13, 1.62, 0.6]} />
      <mesh geometry={nodes.R3.geometry} material={materials.r_3} position={[43.21, 1.65, -49.43]} scale={[1, 1, 0.6]} />
      <mesh geometry={nodes.R5.geometry} material={materials.r_5} position={[42.72, 1.65, -49.2]} scale={[0.96, 1, 0.6]} />
    </group>
  )
}

useGLTF.preload('/Webgl_tmp.glb')
